//General
export const ABRIR_BACKDROP = 'ABRIR_BACKDROP'
export const CERRAR_BACKDROP = 'CERRAR_BACKDROP'
export const ABRIR_MENU = 'ABRIR_MENU'
export const CERRAR_MENU = 'CERRAR_MENU'
export const MOSTRAR_ENCABEZADO = 'MOSTRAR_ENCABEZADO'
export const OCULTAR_ENCABEZADO = 'OCULTAR_ENCABEZADO'
export const SET_DATOS_USUARIO_LOGUEADO = 'SET_DATOS_USUARIO_LOGUEADO'
export const SET_DATOS_USUARIO_NO_LOGUEADO = 'SET_DATOS_USUARIO_NO_LOGUEADO'
export const MOSTRAR_CAMBIO_CONTRASENA_OLVIDADA = 'MOSTRAR_CAMBIO_CONTRASENA_OLVIDADA'
export const SET_TOKEN_CAMBIO_CONTRASENA_OLVIDADA = 'SET_TOKEN_CAMBIO_CONTRASENA_OLVIDADA'
export const SET_TOKEN_DECODIFICADO_CAMBIO_CONTRASENA_OLVIDADA = 
    'SET_TOKEN_DECODIFICADO_CAMBIO_CONTRASENA_OLVIDADA'

//Dashboard
export const SET_DASHBOARD_LISTADO_SEDE = 'SET_DASHBOARD_LISTADO_SEDE'

//Usuario
export const SET_USUARIO_LISTADO_ROL_USUARIO= 'SET_USUARIO_LISTADO_ROL_USUARIO'
export const ABRIR_FORMULARIO_USUARIO = 'ABRIR_FORMULARIO_USUARIO'
export const CERRAR_FORMULARIO_USUARIO = 'CERRAR_FORMULARIO_USUARIO'
export const SET_USUARIO_FORMULARIO_USUARIO = 'SET_USUARIO_FORMULARIO_USUARIO'
export const SET_USUARIO_FORMULARIO_USUARIO_VACIO = 'SET_USUARIO_FORMULARIO_USUARIO_VACIO'
export const SET_USUARIO_FORMULARIO_USUARIO_ANTERIOR = 'SET_USUARIO_FORMULARIO_USUARIO_ANTERIOR'
export const SET_USUARIO_FORMULARIO_POR_CAMPO = 'SET_USUARIO_FORMULARIO_POR_CAMPO'

//Sede Empresa
export const ABRIR_FORMULARIO_SEDE_EMPRESA = 'ABRIR_FORMULARIO_SEDE_EMPRESA'
export const CERRAR_FORMULARIO_SEDE_EMPRESA = 'CERRAR_FORMULARIO_SEDE_EMPRESA'
export const SET_SEDE_EMPRESA_FORMULARIO_SEDE_EMPRESA = 'SET_SEDE_EMPRESA_FORMULARIO_SEDE_EMPRESA'
export const SET_SEDE_EMPRESA_FORMULARIO_SEDE_EMPRESA_VACIO = 
    'SET_SEDE_EMPRESA_FORMULARIO_SEDE_EMPRESA_VACIO'
export const SET_SEDE_EMPRESA_FORMULARIO_SEDE_EMPRESA_ANTERIOR = 
    'SET_SEDE_EMPRESA_FORMULARIO_SEDE_EMPRESA_ANTERIOR'
export const SET_SEDE_EMPRESA_FORMULARIO_POR_CAMPO = 'SET_SEDE_EMPRESA_FORMULARIO_POR_CAMPO'

//Area Empresa
export const SET_AREA_EMPRESA_LISTADO_SEDE_EMPRESA = 
    'SET_AREA_EMPRESA_LISTADO_SEDE_EMPRESA'
export const ABRIR_FORMULARIO_AREA_EMPRESA = 'ABRIR_FORMULARIO_AREA_EMPRESA'
export const CERRAR_FORMULARIO_AREA_EMPRESA = 'CERRAR_FORMULARIO_AREA_EMPRESA'
export const SET_AREA_EMPRESA_FORMULARIO_AREA_EMPRESA = 'SET_AREA_EMPRESA_FORMULARIO_AREA_EMPRESA'
export const SET_AREA_EMPRESA_FORMULARIO_AREA_EMPRESA_VACIO = 
    'SET_AREA_EMPRESA_FORMULARIO_AREA_EMPRESA_VACIO'
export const SET_AREA_EMPRESA_FORMULARIO_AREA_EMPRESA_ANTERIOR = 
    'SET_AREA_EMPRESA_FORMULARIO_AREA_EMPRESA_ANTERIOR'
export const SET_AREA_EMPRESA_FORMULARIO_POR_CAMPO = 'SET_AREA_EMPRESA_FORMULARIO_POR_CAMPO'

//Nomenclatura Equipo Biométrico
export const ABRIR_FORMULARIO_NOMENCLATURA = 'ABRIR_FORMULARIO_NOMENCLATURA'
export const CERRAR_FORMULARIO_NOMENCLATURA = 'CERRAR_FORMULARIO_NOMENCLATURA'
export const SET_NOMENCLATURA_FORMULARIO_NOMENCLATURA = 'SET_NOMENCLATURA_FORMULARIO_NOMENCLATURA'
export const SET_NOMENCLATURA_FORMULARIO_NOMENCLATURA_VACIO = 
    'SET_NOMENCLATURA_FORMULARIO_NOMENCLATURA_VACIO'
export const SET_NOMENCLATURA_FORMULARIO_NOMENCLATURA_ANTERIOR = 
    'SET_NOMENCLATURA_FORMULARIO_NOMENCLATURA_ANTERIOR'
export const SET_NOMENCLATURA_FORMULARIO_POR_CAMPO = 'SET_NOMENCLATURA_FORMULARIO_POR_CAMPO'

//Equipo Biométrico
export const SET_EQUIPO_BIOMETRICO_LISTADO_SEDE_EMPRESA = 'SET_EQUIPO_BIOMETRICO_LISTADO_SEDE_EMPRESA'
export const SET_EQUIPO_BIOMETRICO_LISTADO_NOMENCLATURA = 'SET_EQUIPO_BIOMETRICO_LISTADO_NOMENCLATURA'
export const ABRIR_FORMULARIO_EQUIPO_BIOMETRICO = 'ABRIR_FORMULARIO_EQUIPO_BIOMETRICO'
export const CERRAR_FORMULARIO_EQUIPO_BIOMETRICO = 'CERRAR_FORMULARIO_EQUIPO_BIOMETRICO'
export const SET_EQUIPO_BIOMETRICO_FORMULARIO_EQUIPO_BIOMETRICO = 
    'SET_EQUIPO_BIOMETRICO_FORMULARIO_EQUIPO_BIOMETRICO'
export const SET_EQUIPO_BIOMETRICO_FORMULARIO_EQUIPO_BIOMETRICO_VACIO = 
    'SET_EQUIPO_BIOMETRICO_FORMULARIO_EQUIPO_BIOMETRICO_VACIO'
export const SET_EQUIPO_BIOMETRICO_FORMULARIO_EQUIPO_BIOMETRICO_ANTERIOR = 
    'SET_EQUIPO_BIOMETRICO_FORMULARIO_EQUIPO_BIOMETRICO_ANTERIOR'
export const SET_EQUIPO_BIOMETRICO_FORMULARIO_POR_CAMPO = 'SET_EQUIPO_BIOMETRICO_FORMULARIO_POR_CAMPO'
export const ABRIR_MODAL_APERTURA_PUERTA_EQUIPO_BIOMETRICO = 'ABRIR_MODAL_APERTURA_PUERTA_EQUIPO_BIOMETRICO'
export const CERRAR_MODAL_APERTURA_PUERTA_EQUIPO_BIOMETRICO = 'CERRAR_MODAL_APERTURA_PUERTA_EQUIPO_BIOMETRICO'
export const SET_DATOS_APERTURA_PUERTA_EQUIPO_BIOMETRICO = 'SET_DATOS_APERTURA_PUERTA_EQUIPO_BIOMETRICO'

//Personal Empresa
export const SET_PERSONAL_EMPRESA_LISTADO_SEDE_EMPRESA = 'SET_PERSONAL_EMPRESA_LISTADO_SEDE_EMPRESA'
export const SET_PERSONAL_EMPRESA_LISTADO_SEDE_EMPRESA_AREA_EMPRESA = 
    'SET_PERSONAL_EMPRESA_LISTADO_SEDE_EMPRESA_AREA_EMPRESA'
export const SET_PERSONAL_EMPRESA_LISTADO_AREA_EMPRESA_SELECCIONADO = 
    'SET_PERSONAL_EMPRESA_LISTADO_AREA_EMPRESA_SELECCIONADO'
export const SET_PERSONAL_EMPRESA_LISTADO_AREA_EMPRESA_ABIERTO_CERRADO = 
    'SET_PERSONAL_EMPRESA_LISTADO_AREA_EMPRESA_ABIERTO_CERRADO'
export const ABRIR_FORMULARIO_PERSONAL_EMPRESA = 'ABRIR_FORMULARIO_PERSONAL_EMPRESA'
export const CERRAR_FORMULARIO_PERSONAL_EMPRESA = 'CERRAR_FORMULARIO_PERSONAL_EMPRESA'
export const SET_PERSONAL_EMPRESA_FORMULARIO_PERSONAL_EMPRESA = 
    'SET_PERSONAL_EMPRESA_FORMULARIO_PERSONAL_EMPRESA'
export const SET_PERSONAL_EMPRESA_FORMULARIO_PERSONAL_EMPRESA_VACIO = 
    'SET_PERSONAL_EMPRESA_FORMULARIO_PERSONAL_EMPRESA_VACIO'
export const SET_PERSONAL_EMPRESA_FORMULARIO_PERSONAL_EMPRESA_ANTERIOR = 
    'SET_PERSONAL_EMPRESA_FORMULARIO_PERSONAL_EMPRESA_ANTERIOR'
export const SET_PERSONAL_EMPRESA_FORMULARIO_POR_CAMPO = 'SET_PERSONAL_EMPRESA_FORMULARIO_POR_CAMPO'
export const ABRIR_FORMULARIO_PERSONAL_EMPRESA_SELECTOR_AREA = 
    'ABRIR_FORMULARIO_PERSONAL_EMPRESA_SELECTOR_AREA'
export const CERRAR_FORMULARIO_PERSONAL_EMPRESA_SELECTOR_AREA = 
    'CERRAR_FORMULARIO_PERSONAL_EMPRESA_SELECTOR_AREA'
export const ABRIR_FORMULARIO_PERSONAL_EMPRESA_CAPTURADOR_IRIS = 
    'ABRIR_FORMULARIO_PERSONAL_EMPRESA_CAPTURADOR_IRIS'
export const CERRAR_FORMULARIO_PERSONAL_EMPRESA_CAPTURADOR_IRIS = 
    'CERRAR_FORMULARIO_PERSONAL_EMPRESA_CAPTURADOR_IRIS'
export const ABRIR_COMPROBAR_RECONOCIMIENTO_IRIS = 'ABRIR_COMPROBAR_RECONOCIMIENTO_IRIS'
export const CERRAR_COMPROBAR_RECONOCIMIENTO_IRIS = 'CERRAR_COMPROBAR_RECONOCIMIENTO_IRIS'

//Reporte
export const ABRIR_VISUALIZADOR_IMAGEN_PERSONAL_NO_REGISTRADO = 
    'ABRIR_VISUALIZADOR_IMAGEN_PERSONAL_NO_REGISTRADO'
export const CERRAR_VISUALIZADOR_IMAGEN_PERSONAL_NO_REGISTRADO = 
    'CERRAR_VISUALIZADOR_IMAGEN_PERSONAL_NO_REGISTRADO'