/*
PROYECTO: Uso de Sistema de Reconocimiento de Iris basado en Deep Learning para la Identificación 
Humana en el Control de Acceso al área de Tesorería del Gobierno Regional de Tacna - Tacna 2020.
AUTOR: Luis Eduardo Mamani Bedregal
*/
CREATE DATABASE SRICA; /*SRICA_DEV*/
USE SRICA; /*SRICA_DEV*/

CREATE TABLE SI_MODULO_SISTEMA
(
	COD_MODULO_SISTEMA INT NOT NULL,
    DES_MODULO_SISTEMA VARCHAR(200) NOT NULL
);

ALTER TABLE SI_MODULO_SISTEMA
ADD CONSTRAINT PK_SI_MODULO_SISTEMA_COD_MODULO_SISTEMA
PRIMARY KEY (COD_MODULO_SISTEMA);

ALTER TABLE SI_MODULO_SISTEMA
MODIFY COLUMN COD_MODULO_SISTEMA INT AUTO_INCREMENT;

CREATE TABLE SI_RECURSO_SISTEMA
(
	COD_RECURSO_SISTEMA INT NOT NULL,
    DES_RECURSO_SISTEMA VARCHAR(200) NOT NULL
);

ALTER TABLE SI_RECURSO_SISTEMA
ADD CONSTRAINT PK_SI_RECURSO_SISTEMA_COD_RECURSO_SISTEMA
PRIMARY KEY (COD_RECURSO_SISTEMA);

ALTER TABLE SI_RECURSO_SISTEMA
MODIFY COLUMN COD_RECURSO_SISTEMA INT AUTO_INCREMENT;

CREATE TABLE SI_TIPO_EVENTO_SISTEMA
(
	COD_TIPO_EVENTO_SISTEMA INT NOT NULL,
    DES_TIPO_EVENTO_SISTEMA VARCHAR(20) NOT NULL
);

ALTER TABLE SI_TIPO_EVENTO_SISTEMA
ADD CONSTRAINT PK_SI_TIPO_EVENTO_SISTEMA_COD_TIPO_EVENTO_SISTEMA
PRIMARY KEY (COD_TIPO_EVENTO_SISTEMA);

ALTER TABLE SI_TIPO_EVENTO_SISTEMA
MODIFY COLUMN COD_TIPO_EVENTO_SISTEMA INT AUTO_INCREMENT;

CREATE TABLE SI_ACCION_SISTEMA
(
	COD_ACCION_SISTEMA INT NOT NULL,
    DES_ACCION_SISTEMA VARCHAR(200) NOT NULL
);

ALTER TABLE SI_ACCION_SISTEMA
ADD CONSTRAINT PK_SI_ACCION_SISTEMA_COD_ACCION_SISTEMA
PRIMARY KEY (COD_ACCION_SISTEMA);

ALTER TABLE SI_ACCION_SISTEMA
MODIFY COLUMN COD_ACCION_SISTEMA INT AUTO_INCREMENT;

CREATE TABLE US_ROL_USUARIO
(
	COD_ROL_USUARIO INT NOT NULL,
    DES_ROL_USUARIO VARCHAR(20) NOT NULL,
    IND_ESTADO BOOLEAN NOT NULL
);

ALTER TABLE US_ROL_USUARIO
ADD CONSTRAINT PK_US_ROL_USUARIO_COD_ROL_USUARIO
PRIMARY KEY (COD_ROL_USUARIO);

ALTER TABLE US_ROL_USUARIO
MODIFY COLUMN COD_ROL_USUARIO INT AUTO_INCREMENT;

CREATE TABLE US_USUARIO
(
	COD_USUARIO INT NOT NULL,
    COD_ROL_USUARIO INT NOT NULL,
    USU_USUARIO CHAR(8) NOT NULL,
    USU_CONTRASENA VARCHAR(64) NOT NULL,
    NOM_USUARIO VARCHAR(40) NOT NULL,
    APE_USUARIO VARCHAR(40) NOT NULL,
    DES_CORREO_ELECTRONICO VARCHAR(64) NOT NULL,
    IND_CORREO_POR_DEFECTO BOOLEAN NOT NULL,
    IND_CONTRASENA_POR_DEFECTO BOOLEAN NOT NULL,
    IND_ESTADO BOOLEAN NOT NULL
);

ALTER TABLE US_USUARIO
ADD CONSTRAINT PK_US_USUARIO_COD_USUARIO
PRIMARY KEY (COD_USUARIO);

ALTER TABLE US_USUARIO
MODIFY COLUMN COD_USUARIO INT AUTO_INCREMENT;

ALTER TABLE US_USUARIO
ADD CONSTRAINT FK_US_USUARIO_VS_US_ROL_USUARIO_00
FOREIGN KEY (COD_ROL_USUARIO) REFERENCES US_ROL_USUARIO(COD_ROL_USUARIO);

ALTER TABLE US_USUARIO
ADD CONSTRAINT UQ_US_USUARIO_USU_USUARIO
UNIQUE (USU_USUARIO);

ALTER TABLE US_USUARIO
ALTER USU_CONTRASENA SET DEFAULT '';

ALTER TABLE US_USUARIO
ALTER DES_CORREO_ELECTRONICO SET DEFAULT 'srica@cambiarcorreo.com';

CREATE TABLE SE_SEDE
(
	COD_SEDE INT NOT NULL,
    DES_SEDE VARCHAR(40) NOT NULL,
    IND_REGISTRO_PARA_SIN_ASIGNACION BOOLEAN NOT NULL,
	IND_ESTADO BOOLEAN NOT NULL
);

ALTER TABLE SE_SEDE
ADD CONSTRAINT PK_SE_SEDE_COD_SEDE
PRIMARY KEY (COD_SEDE);

ALTER TABLE SE_SEDE
MODIFY COLUMN COD_SEDE INT AUTO_INCREMENT;

CREATE TABLE AR_AREA
(
	COD_AREA INT NOT NULL,
    COD_SEDE INT NOT NULL,
    DES_AREA VARCHAR(40) NOT NULL,
    IND_REGISTRO_PARA_SIN_ASIGNACION BOOLEAN NOT NULL,
    IND_ESTADO BOOLEAN NOT NULL
);

ALTER TABLE AR_AREA
ADD CONSTRAINT PK_AR_AREA_COD_AREA
PRIMARY KEY (COD_AREA);

ALTER TABLE AR_AREA
MODIFY COLUMN COD_AREA INT AUTO_INCREMENT;

ALTER TABLE AR_AREA
ADD CONSTRAINT FK_AR_AREA_VS_SE_SEDE_00
FOREIGN KEY (COD_SEDE) REFERENCES SE_SEDE(COD_SEDE);

CREATE TABLE EB_NOMENCLATURA_EQUIPO_BIOMETRICO
(
	COD_NOMENCLATURA INT NOT NULL,
    DES_NOMENCLATURA CHAR(3) NOT NULL,
    IND_REGISTRO_PARA_SIN_ASIGNACION BOOLEAN NOT NULL,
    IND_ESTADO BOOLEAN NOT NULL
);

ALTER TABLE EB_NOMENCLATURA_EQUIPO_BIOMETRICO
ADD CONSTRAINT PK_EB_NOMENCLATURA_EQUIPO_BIOMETRICO_COD_NOMENCLATURA
PRIMARY KEY (COD_NOMENCLATURA);

ALTER TABLE EB_NOMENCLATURA_EQUIPO_BIOMETRICO
MODIFY COLUMN COD_NOMENCLATURA INT AUTO_INCREMENT;

ALTER TABLE EB_NOMENCLATURA_EQUIPO_BIOMETRICO
ADD CONSTRAINT UQ_EB_NOMENCLATURA_EQUIPO_BIOMETRICO_DES_NOMENCLATURA
UNIQUE (DES_NOMENCLATURA);

CREATE TABLE EB_EQUIPO_BIOMETRICO
(
	COD_EQUIPO_BIOMETRICO INT NOT NULL,
    COD_NOMENCLATURA INT NOT NULL,
    NOM_EQUIPO_BIOMETRICO VARCHAR(15) NOT NULL,
    DES_DIRECCION_RED VARCHAR(15) NOT NULL,
    COD_AREA INT NOT NULL,
    DES_DIRECCION_FISICA VARCHAR(64) NOT NULL,
    IND_ESTADO BOOLEAN NOT NULL
);

ALTER TABLE EB_EQUIPO_BIOMETRICO
ADD CONSTRAINT PK_EB_EQUIPO_BIOMETRICO_COD_EQUIPO_BIOMETRICO
PRIMARY KEY (COD_EQUIPO_BIOMETRICO);

ALTER TABLE EB_EQUIPO_BIOMETRICO
MODIFY COLUMN COD_EQUIPO_BIOMETRICO INT AUTO_INCREMENT;

ALTER TABLE EB_EQUIPO_BIOMETRICO
ADD CONSTRAINT FK_EB_EQUIPO_BIOMETRICO_VS_AR_AREA_00
FOREIGN KEY (COD_AREA) REFERENCES AR_AREA(COD_AREA);

ALTER TABLE EB_EQUIPO_BIOMETRICO
ADD CONSTRAINT FK_EB_EQUIPO_BIOMETRICO_VS_EB_NOMENCLATURA_EQUIPO_BIOMETRICO_01
FOREIGN KEY (COD_NOMENCLATURA) REFERENCES EB_NOMENCLATURA_EQUIPO_BIOMETRICO(COD_NOMENCLATURA);

ALTER TABLE EB_EQUIPO_BIOMETRICO
ADD CONSTRAINT UQ_EB_EQUIPO_BIOMETRICO_NOM_EQUIPO_BIOMETRICO
UNIQUE (NOM_EQUIPO_BIOMETRICO);

ALTER TABLE EB_EQUIPO_BIOMETRICO
ADD CONSTRAINT UQ_EB_EQUIPO_BIOMETRICO_DES_DIRECCION_RED
UNIQUE (DES_DIRECCION_RED);

ALTER TABLE EB_EQUIPO_BIOMETRICO
ADD CONSTRAINT UQ_EB_EQUIPO_BIOMETRICO_DES_DIRECCION_FISICA
UNIQUE (DES_DIRECCION_FISICA);

CREATE TABLE PE_PERSONAL_EMPRESA
(
	COD_PERSONAL INT NOT NULL,
    NUM_DNI_PERSONAL CHAR(8) NOT NULL,
    NOM_PERSONAL VARCHAR(40) NOT NULL,
    APE_PERSONAL VARCHAR(40) NOT NULL,
    IMG_IRIS_CODIFICADO LONGBLOB NULL,
    IND_ESTADO BOOLEAN NOT NULL
);

ALTER TABLE PE_PERSONAL_EMPRESA
ADD CONSTRAINT PK_PE_PERSONAL_EMPRESA_COD_PERSONAL
PRIMARY KEY (COD_PERSONAL);

ALTER TABLE PE_PERSONAL_EMPRESA
MODIFY COLUMN COD_PERSONAL INT AUTO_INCREMENT;

ALTER TABLE PE_PERSONAL_EMPRESA
ADD CONSTRAINT UQ_PE_PERSONAL_EMPRESA_NUM_DNI_PERSONAL
UNIQUE (NUM_DNI_PERSONAL);

CREATE TABLE PE_PERSONAL_EMPRESA_X_AREA
(
	COD_PERSONAL_EMPRESA_X_AREA INT NOT NULL,
    COD_PERSONAL INT NOT NULL,
    COD_AREA INT NOT NULL,
    IND_ESTADO BOOLEAN NOT NULL
);

ALTER TABLE PE_PERSONAL_EMPRESA_X_AREA
ADD CONSTRAINT PK_PE_PERSONAL_EMPRESA_X_AREA_COD_PERSONAL_EMPRESA_X_AREA
PRIMARY KEY (COD_PERSONAL_EMPRESA_X_AREA);

ALTER TABLE PE_PERSONAL_EMPRESA_X_AREA
MODIFY COLUMN COD_PERSONAL_EMPRESA_X_AREA INT AUTO_INCREMENT;

ALTER TABLE PE_PERSONAL_EMPRESA_X_AREA
ADD CONSTRAINT FK_PE_PERSONAL_EMPRESA_X_AREA_VS_PE_PERSONAL_EMPRESA_00
FOREIGN KEY (COD_PERSONAL) REFERENCES PE_PERSONAL_EMPRESA(COD_PERSONAL);

ALTER TABLE PE_PERSONAL_EMPRESA_X_AREA
ADD CONSTRAINT FK_PE_PERSONAL_EMPRESA_X_AREA_VS_AR_AREA_01
FOREIGN KEY (COD_AREA) REFERENCES AR_AREA(COD_AREA);

CREATE TABLE SI_RESULTADO_ACCESO
(
	COD_RESULTADO_ACCESO INT NOT NULL,
    DES_RESULTADO_ACCESO VARCHAR(20) NOT NULL
);

ALTER TABLE SI_RESULTADO_ACCESO
ADD CONSTRAINT PK_SI_RESULTADO_ACCESO_COD_RESULTADO_ACCESO
PRIMARY KEY (COD_RESULTADO_ACCESO);

ALTER TABLE SI_RESULTADO_ACCESO
MODIFY COLUMN COD_RESULTADO_ACCESO INT AUTO_INCREMENT;

CREATE TABLE BT_BITACORA_ACCION_SISTEMA
(
	COD_BITACORA INT NOT NULL,
    COD_USUARIO INT NOT NULL,
    USU_USUARIO VARCHAR(8) NOT NULL,
    NOM_USUARIO VARCHAR(40) NOT NULL,
    APE_USUARIO VARCHAR(40) NOT NULL,
    COD_ROL_USUARIO INT NOT NULL,
    COD_MODULO_SISTEMA INT NOT NULL,
    COD_RECURSO_SISTEMA INT NOT NULL,
    COD_TIPO_EVENTO_SISTEMA INT NOT NULL,
    COD_ACCION_SISTEMA INT NOT NULL,
    DES_RESULTADO_ACCION LONGTEXT NOT NULL,
    VAL_ANTERIOR LONGTEXT NOT NULL,
    VAL_ACTUAL LONGTEXT NOT NULL,
    FEC_ACCION DATETIME NOT NULL
);

ALTER TABLE BT_BITACORA_ACCION_SISTEMA
ADD CONSTRAINT PK_BT_BITACORA_ACCION_SISTEMA_COD_BITACORA
PRIMARY KEY (COD_BITACORA);

ALTER TABLE BT_BITACORA_ACCION_SISTEMA
MODIFY COLUMN COD_BITACORA INT AUTO_INCREMENT;

ALTER TABLE BT_BITACORA_ACCION_SISTEMA
ADD CONSTRAINT FK_BT_BITACORA_ACCION_SISTEMA_VS_SI_MODULO_SISTEMA_00
FOREIGN KEY (COD_MODULO_SISTEMA) REFERENCES SI_MODULO_SISTEMA(COD_MODULO_SISTEMA);

ALTER TABLE BT_BITACORA_ACCION_SISTEMA
ADD CONSTRAINT FK_BT_BITACORA_ACCION_SISTEMA_VS_SI_RECURSO_SISTEMA_01
FOREIGN KEY (COD_RECURSO_SISTEMA) REFERENCES SI_RECURSO_SISTEMA(COD_RECURSO_SISTEMA);

ALTER TABLE BT_BITACORA_ACCION_SISTEMA
ADD CONSTRAINT FK_BT_BITACORA_ACCION_SISTEMA_VS_SI_TIPO_EVENTO_SISTEMA_02
FOREIGN KEY (COD_TIPO_EVENTO_SISTEMA) REFERENCES SI_TIPO_EVENTO_SISTEMA(COD_TIPO_EVENTO_SISTEMA);

ALTER TABLE BT_BITACORA_ACCION_SISTEMA
ADD CONSTRAINT FK_BT_BITACORA_ACCION_SISTEMA_VS_SI_ACCION_SISTEMA_03
FOREIGN KEY (COD_ACCION_SISTEMA) REFERENCES SI_ACCION_SISTEMA(COD_ACCION_SISTEMA);

ALTER TABLE BT_BITACORA_ACCION_SISTEMA
ADD CONSTRAINT FK_BT_BITACORA_ACCION_SISTEMA_VS_US_ROL_USUARIO_04
FOREIGN KEY (COD_ROL_USUARIO) REFERENCES US_ROL_USUARIO(COD_ROL_USUARIO);

ALTER TABLE BT_BITACORA_ACCION_SISTEMA
ALTER COD_USUARIO SET DEFAULT 0;

ALTER TABLE BT_BITACORA_ACCION_SISTEMA
ALTER USU_USUARIO SET DEFAULT '';

ALTER TABLE BT_BITACORA_ACCION_SISTEMA
ALTER NOM_USUARIO SET DEFAULT '';

ALTER TABLE BT_BITACORA_ACCION_SISTEMA
ALTER APE_USUARIO SET DEFAULT '';

ALTER TABLE BT_BITACORA_ACCION_SISTEMA
ALTER FEC_ACCION SET DEFAULT '1900-01-01 00:00:00';

CREATE TABLE BT_BITACORA_ACCION_EQUIPO_BIOMETRICO
(
	COD_BITACORA INT NOT NULL,
    COD_PERSONAL INT NOT NULL,
    NUM_DNI_PERSONAL VARCHAR(8) NOT NULL,
    NOM_PERSONAL VARCHAR(40) NOT NULL,
    APE_PERSONAL VARCHAR(40) NOT NULL,
    COD_SEDE INT NOT NULL,
    DES_SEDE VARCHAR(40) NOT NULL,
    COD_AREA INT NOT NULL,
    DES_AREA VARCHAR(40) NOT NULL,
    NOM_EQUIPO_BIOMETRICO VARCHAR(15) NOT NULL,
    COD_RESULTADO_ACCESO INT NOT NULL,
    DES_RESULTADO_ACCION LONGTEXT NOT NULL,
    FEC_ACCESO DATETIME NOT NULL,
    IMG_PERSONAL_NO_REGISTRADO LONGBLOB NULL
);

ALTER TABLE BT_BITACORA_ACCION_EQUIPO_BIOMETRICO
ADD CONSTRAINT PK_BT_BITACORA_ACCION_EQUIPO_BIOMETRICO_COD_BITACORA
PRIMARY KEY (COD_BITACORA);

ALTER TABLE BT_BITACORA_ACCION_EQUIPO_BIOMETRICO
MODIFY COLUMN COD_BITACORA INT AUTO_INCREMENT;

ALTER TABLE BT_BITACORA_ACCION_EQUIPO_BIOMETRICO
ADD CONSTRAINT FK_BT_BIT_ACCION_EQUIPO_BIO_VS_SI_RESULTADO_ACCESO_00
FOREIGN KEY (COD_RESULTADO_ACCESO) REFERENCES SI_RESULTADO_ACCESO(COD_RESULTADO_ACCESO);

ALTER TABLE BT_BITACORA_ACCION_EQUIPO_BIOMETRICO
ALTER COD_PERSONAL SET DEFAULT 0;

ALTER TABLE BT_BITACORA_ACCION_EQUIPO_BIOMETRICO
ALTER NUM_DNI_PERSONAL SET DEFAULT '';

ALTER TABLE BT_BITACORA_ACCION_EQUIPO_BIOMETRICO
ALTER NOM_PERSONAL SET DEFAULT '';

ALTER TABLE BT_BITACORA_ACCION_EQUIPO_BIOMETRICO
ALTER APE_PERSONAL SET DEFAULT '';

ALTER TABLE BT_BITACORA_ACCION_EQUIPO_BIOMETRICO
ALTER COD_SEDE SET DEFAULT 0;

ALTER TABLE BT_BITACORA_ACCION_EQUIPO_BIOMETRICO
ALTER DES_SEDE SET DEFAULT '';

ALTER TABLE BT_BITACORA_ACCION_EQUIPO_BIOMETRICO
ALTER COD_AREA SET DEFAULT 0;

ALTER TABLE BT_BITACORA_ACCION_EQUIPO_BIOMETRICO
ALTER DES_AREA SET DEFAULT '';

ALTER TABLE BT_BITACORA_ACCION_EQUIPO_BIOMETRICO
ALTER NOM_EQUIPO_BIOMETRICO SET DEFAULT '';

ALTER TABLE BT_BITACORA_ACCION_EQUIPO_BIOMETRICO
ALTER FEC_ACCESO SET DEFAULT '1900-01-01 00:00:00';

/*
Datos iniciales
*/

INSERT INTO US_ROL_USUARIO (DES_ROL_USUARIO,IND_ESTADO) 
VALUES ('Administrador', 1),
('Usuario Básico', 1),
('Sin Rol', 0);

INSERT INTO SE_SEDE (DES_SEDE, IND_REGISTRO_PARA_SIN_ASIGNACION, IND_ESTADO)
VALUES ('---', 1, 1);

INSERT INTO AR_AREA (COD_SEDE, DES_AREA, IND_REGISTRO_PARA_SIN_ASIGNACION, IND_ESTADO)
VALUES (1, '---', 1, 1);

INSERT INTO EB_NOMENCLATURA_EQUIPO_BIOMETRICO (DES_NOMENCLATURA, IND_REGISTRO_PARA_SIN_ASIGNACION, IND_ESTADO)
VALUES ('---', 1, 1);
INSERT INTO EB_NOMENCLATURA_EQUIPO_BIOMETRICO (DES_NOMENCLATURA, IND_REGISTRO_PARA_SIN_ASIGNACION, IND_ESTADO)
VALUES ('SRI', 0, 1);

INSERT INTO SI_MODULO_SISTEMA (DES_MODULO_SISTEMA)
VALUES ('Seguridad del Sistema'),
('Perfil de Usuario'),
('Dashboard del Sistema'),
('Usuario del sistema'),
('Sede de la Empresa'),
('Área de la Empresa'),
('Equipo Biométrico'),
('Personal de la Empresa'),
('Reporte');

INSERT INTO SI_RECURSO_SISTEMA (DES_RECURSO_SISTEMA)
VALUES ('Seguridad del Sistema'),
('Perfil de Usuario'),
('Dashboard del Sistema'),
('Usuario del sistema'),
('Sede de la Empresa'),
('Área de la Empresa'),
('Nomenclatura'),
('Equipo Biométrico'),
('Personal de la Empresa'),
('Reporte del Sistema'),
('Reporte de Acción del Sistema'),
('Reporte de Acción de Equipos Biométricos');

INSERT INTO SI_TIPO_EVENTO_SISTEMA (DES_TIPO_EVENTO_SISTEMA)
VALUES ('Error'),
('Validación'),
('Correcto');

INSERT INTO SI_ACCION_SISTEMA (DES_ACCION_SISTEMA)
VALUES ('Acceso al Sistema'),
('Sesión Finalizada'),
('Recuperación de Contraseña'),
('Cambio de Contraseña Olvidada'),
('Cambio de Datos por Defecto'),
('Obtención de Datos'),
('Registro de Datos'),
('Modificación de Datos'),
('Inactivación de Registros'),
('Activación de Registros'),
('Acceso a Equipo Biométrico'),
('Apertura de Puerta de Acceso'),
('Registro Masivo de Datos'),
('Generación de Reporte'),
('Exportación de Reporte');

INSERT INTO SI_RESULTADO_ACCESO (DES_RESULTADO_ACCESO)
VALUES ('Concedido'),
('Denegado'),
('Error');

INSERT INTO EB_EQUIPO_BIOMETRICO (COD_NOMENCLATURA, NOM_EQUIPO_BIOMETRICO, DES_DIRECCION_RED, COD_AREA, DES_DIRECCION_FISICA, IND_ESTADO)
VALUES (2, 'SRI-EQUI-BIO-01', '192.168.0.25', 1, 'mSMbyGTp/BUWEsxlMEKtpMjF40iaatYTHn8ZnDXk/Jc=', 1)